services:
  - type: web
    name: lexnote
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20
    envVars:
      - key: NODE_ENV
        value: production
      - key: NO_PROXY
        value: '*'
