services:
  - type: web
    name: lexnote
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
